apiVersion: v1
kind: Service
metadata:
  name:  zakaa-notification-service
spec:
  selector:
    app: notification-service
  ports:
  - name:  notification-service
    protocol: TCP
    port:  3003
    targetPort: 3003