apiVersion: v1
kind: Service
metadata:
  name:  zakaa-payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name:  payment-service
    protocol: TCP
    port:  3005
    targetPort: 3005