apiVersion: apps/v1
kind: Deployment
metadata:
  name: zakaa-auth-deployment
  labels:
    name:  auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - image: nabeelncz/zakaa-auth:latest
        name: auth-service
        envFrom:
          - configMapRef:
              name: auth-service-config